apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: petstore
  namespace: bookinfo-frontends
  labels:
    expose: "true"
spec:
  hosts:
  - petstore.swagger.io
  ports:
  - name: http
    number: 80
    protocol: HTTP
  - name: https
    number: 443
    protocol: HTTPS
    clientsideTls: {}