apiVersion: v1
kind: Secret
metadata:
  name: user2
  namespace: bookinfo-frontends
  labels:
    auth: api-key
type: extauth.solo.io/apikey
stringData:
  api-key: apikey2
  user-id: user2
  user-email: user2@solo.io
  usagePlan: gold