Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8888

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "8"
    vb.memory = "16384"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo 'Defaults env_keep += "SSH_AUTH_SOCK"' >> /etc/sudoers
    adduser --disabled-password --gecos "" solo
    echo "solo ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/solo
    usermod -a -G vagrant solo
    cp -pr /home/vagrant/.ssh /home/solo/
    chown -R solo:solo /home/solo/.ssh
  SHELL

  VAGRANT_COMMAND = ARGV[0]
  if VAGRANT_COMMAND == "ssh"
      config.ssh.forward_agent = true
      config.ssh.username = 'solo'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible-playbook.yml"
    ansible.compatibility_mode = "2.0"
  end
end
