Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "8"
    vb.memory = "16384"
  end

  VAGRANT_COMMAND = ARGV[0]
  if VAGRANT_COMMAND == "ssh"
      config.ssh.forward_agent = true
      config.ssh.username = 'solo'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible-playbook.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      vagrant: "yes"
    }
  end
end
