Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8888

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "8"
    vb.memory = "8192"
  end

  config.vm.provision "shell", inline: <<-SHELL
    adduser --disabled-password --gecos "" solo
    echo "solo ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/solo
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible-playbook.yml"
  end
end
