apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: TransformationPolicy
metadata:
  name: add-api-metadata
  namespace: bookinfo-frontends
spec:
  applyToRoutes:
  - route:
      labels:
        api: "productpage"
  config:
    phase:
      postAuthz:
        priority: 2
    request:
      injaTemplate:
        dynamicMetadataValues:
        - key: api
          value:
            text: productpage