apiVersion: v1
kind: Secret
metadata:
  name: user1
  namespace: bookinfo-frontends
  labels:
    auth: api-key
type: extauth.solo.io/apikey
data:
  api-key: $(echo -n "${API_KEY_USER1}" | base64)
  user-id: dXNlcjE=
  user-email: dXNlcjFAc29sby5pbw==
  usagePlan: Z29sZA==
  prohibitedCountries: $(echo -n "${PROHIBITED_COUNTRY}" | base64)