apiVersion: security.policy.gloo.solo.io/v2
kind: CORSPolicy
metadata:
  name: portal-server
  namespace: gloo-mesh-addons
spec:
  applyToRoutes:
  - route:
      labels:
        portal-server: "true"
  config:
    allowCredentials: true
    allowHeaders:
    - "*"
    allowMethods:
    - GET
    allowOrigins:
    - regex: ".*"