apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: controlplane
  namespace: istio-system
spec:
  profile: minimal
  tag: 1.10.2
  values:
    global:
      # needed for annotating istio metrics with cluster
      multiCluster:
        clusterName: cluster-1  
  meshConfig:
    enableAutoMtls: true
    defaultConfig:
      envoyMetricsService:
        address: enterprise-agent.gloo-mesh:9977      
      proxyMetadata:
        GLOO_MESH_CLUSTER_NAME: cluster-1       
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  components:
    # Istio Gateway feature
    ingressGateways:
    - name: east-west-gateway
      namespace: istio-system
      enabled: true
      label:
        gateway: east-west
      k8s:
        env:
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
        service:
          type: NodePort
          ports:
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
            - port: 15443
              targetPort: 15443
              name: tls
              nodePort: 32000

